In [1]:
from scipy.stats import pearsonr, ttest_ind

import pandas as pd

# Method 1: DATA INTEGRAION

## STEP 1: Load the datasets

In [2]:
# 1. USDA Food Access (Tract Level)
df_usda = pd.read_csv("Food Access Research Atlas.csv", low_memory=False)
df_usda

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72526,56043000200,Wyoming,Washakie County,0,3326,1317,0,57.0,1.71,0,...,593.0,3106.0,6.0,15.0,0.0,27.0,172.0,309.0,61.0,64.0
72527,56043000301,Wyoming,Washakie County,1,2665,1154,0,10.0,0.38,0,...,399.0,2377.0,5.0,23.0,0.0,40.0,220.0,446.0,88.0,41.0
72528,56043000302,Wyoming,Washakie County,1,2542,1021,0,73.0,2.87,0,...,516.0,2312.0,11.0,10.0,1.0,26.0,182.0,407.0,23.0,64.0
72529,56045951100,Wyoming,Weston County,0,3314,1322,0,252.0,7.60,0,...,499.0,3179.0,15.0,10.0,1.0,47.0,62.0,91.0,47.0,34.0
72530,56045951300,Wyoming,Weston County,1,3894,1699,0,61.0,1.57,0,...,650.0,3706.0,6.0,10.0,2.0,44.0,126.0,125.0,34.0,110.0

In [3]:
# 2. CDC PLACES (County Level)
df_cdc = pd.read_csv("PLACES__Local_Data_for_Better_Health,_County_Data_2024_release_20251125.csv", low_memory=False)
df_cdc = df_cdc[df_cdc['StateDesc'] != 'United States']
df_cdc

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation
0,2022,AL,Alabama,Clay,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,11.0,...,9.6,12.4,"14,198","11,235",1027,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-85.8606604130173 33.2693085517833)
1,2022,AL,Alabama,Dale,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,35.6,...,34.8,36.4,"49,544","38,039",1045,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-85.6109266826185 31.4316629601359)
2,2022,AL,Alabama,Jackson,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,5.1,...,4.6,5.6,"52,891","42,087",1071,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-85.9995052603961 34.7796392771775)
3,2022,AL,Alabama,Lauderdale,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,36.5,...,29.6,43.9,"95,878","77,472",1077,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-87.6540983850983 34.9014438477101)
4,2022,AL,Alabama,Lawrence,BRFSS,Disability,Any disability among adults,%,Crude prevalence,40.1,...,35.5,44.7,"33,214","26,022",1079,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-87.3108851040374 34.5216735395968)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240881,2021,WI,Wisconsin,Polk,BRFSS,Health Outcomes,High blood pressure among adults,%,Crude prevalence,34.3,...,29.9,38.8,"45,709","36,755",55095,HLTHOUT,BPHIGH,CrdPrv,High Blood Pressure,POINT (-92.4412755945684 45.4615053795217)
240882,2022,WI,Wisconsin,Trempealeau,BRFSS,Health Outcomes,Depression among adults,%,Age-adjusted prevalence,24.5,...,20.9,28.2,"30,899","23,116",55121,HLTHOUT,DEPRESSION,AgeAdjPrv,Depression,POINT (-91.3584214806691 44.3039450660913)
240883,2022,WI,Wisconsin,Door,BRFSS,Prevention,Visited dentist or dental clinic in the past y...,%,Age-adjusted prevalence,64.3,...,60.1,67.8,"30,526","25,807",55029,PREVENT,DENTAL,AgeAdjPrv,Dental Visit,POINT (-87.3114193001272 44.9500144269812)
240884,2022,WI,Wisconsin,Marathon,BRFSS,Disability,Self-care disability among adults,%,Crude prevalence,3.2,...,2.9,3.5,"137,958","107,333",55073,DISABLT,SELFCARE,CrdPrv,Self-care Disability,POINT (-89.7588560093353 44.8983004431375)
240885,2022,WY,Wyoming,Fremont,BRFSS,Health Risk Behaviors,Binge drinking among adults,%,Crude prevalence,16.4,...,13.5,19.5,"39,472","29,818",56013,RISKBEH,BINGE,CrdPrv,Binge Drinking,POINT (-108.630454608807 43.0406424027024)

In [4]:
# 3. ACS Economic (DP03)
df_acs_econ = pd.read_csv("ACSDP5Y2023.DP03-Data.csv", header=0, low_memory=False).iloc[1:] # skip row 1 (description text)
df_acs_econ

,GEO_ID,NAME,DP03_0001E,DP03_0001M,DP03_0002E,DP03_0002M,DP03_0003E,DP03_0003M,DP03_0004E,DP03_0004M,...,DP03_0133PM,DP03_0134PE,DP03_0134PM,DP03_0135PE,DP03_0135PM,DP03_0136PE,DP03_0136PM,DP03_0137PE,DP03_0137PM,Unnamed: 550
1,0500000US01001,"Autauga County, Alabama",47508,227,28020,890,27070,978,26382,966,...,1.7,11.0,2.1,6.2,1.5,8.4,1.9,22.9,3.6,NaN
2,0500000US01003,"Baldwin County, Alabama",195048,457,113778,1904,113171,1913,109556,1998,...,0.9,10.3,1.1,7.2,1.1,8.1,1.0,22.8,2.1,NaN
3,0500000US01005,"Barbour County, Alabama",20253,94,9085,428,9074,430,8556,440,...,2.7,19.5,3.1,13.1,3.1,19.7,3.2,32.4,5.9,NaN
4,0500000US01007,"Bibb County, Alabama",18176,95,9375,492,9375,492,8439,510,...,2.5,18.6,3.0,11.0,5.0,18.5,3.5,32.2,7.4,NaN
5,0500000US01009,"Blount County, Alabama",47389,152,27189,705,27180,706,25594,751,...,1.6,12.6,1.7,14.5,3.1,11.0,1.8,31.6,4.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,0500000US72145,"Vega Baja Municipio, Puerto Rico",46109,178,19837,842,19815,843,17155,810,...,2.7,39.5,3.1,41.7,3.8,37.7,3.2,60.5,3.7,NaN
3219,0500000US72147,"Vieques Municipio, Puerto Rico",6922,33,2606,499,2606,499,2383,468,...,9.0,55.3,9.9,49.2,13.2,60.2,8.6,56.8,12.5,NaN
3220,0500000US72149,"Villalba Municipio, Puerto Rico",18147,98,7865,459,7823,464,6766,507,...,4.5,40.3,5.2,38.2,5.2,39.2,4.8,59.0,6.1,NaN
3221,0500000US72151,"Yabucoa Municipio, Puerto Rico",25723,130,9469,523,9439,523,8526,562,...,3.8,47.1,4.7,46.1,5.3,46.1,4.4,64.7,4.6,NaN
3222,0500000US72153,"Yauco Municipio, Puerto Rico",28929,86,11860,511,11844,511,10297,552,...,2.9,39.6,3.7,49.6,3.8,39.2,4.1,67.5,4.1,NaN

In [5]:
# 4. ACS Social (DP02)
df_acs_soc = pd.read_csv("ACSDP5Y2023.DP02-Data.csv", header=0, low_memory=False).iloc[1:] # skip row 1 (description text)
df_acs_soc

,GEO_ID,NAME,DP02_0001E,DP02_0001M,DP02_0002E,DP02_0002M,DP02_0003E,DP02_0003M,DP02_0004E,DP02_0004M,...,DP02_0150PM,DP02_0151PE,DP02_0151PM,DP02_0152PE,DP02_0152PM,DP02_0153PE,DP02_0153PM,DP02_0154PE,DP02_0154PM,Unnamed: 618
1,0500000US01001,"Autauga County, Alabama",22523,431,11861,633,5155,381,1055,306,...,0.2,0.0,0.1,22523,(X),96.4,0.7,90.9,1.7,NaN
2,0500000US01003,"Baldwin County, Alabama",94642,1316,53118,1615,16692,1043,4594,588,...,0.2,0.3,0.2,94642,(X),94.8,0.7,89.8,1.0,NaN
3,0500000US01005,"Barbour County, Alabama",9080,315,3572,287,962,173,361,146,...,0.1,1.0,0.7,9080,(X),88.4,2.3,72.3,3.3,NaN
4,0500000US01007,"Bibb County, Alabama",7571,288,3971,359,1187,238,309,120,...,1.2,0.0,0.2,7571,(X),88.5,3.0,81.2,3.6,NaN
5,0500000US01009,"Blount County, Alabama",21977,403,12090,555,4405,408,1181,305,...,0.1,0.1,0.1,21977,(X),91.9,1.3,83.9,1.7,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,0500000US72145,"Vega Baja Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3219,0500000US72147,"Vieques Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3220,0500000US72149,"Villalba Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3221,0500000US72151,"Yabucoa Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3222,0500000US72153,"Yauco Municipio, Puerto Rico",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## STEP 2: Create a unified "FIPS" column

In [6]:
# 1. Clean USDA FIPS
# 'CensusTract' is an integer like 1001020100, but we need 11 digits (01001020100).
# Then we take the first 5 digits (01001) for the County.
df_usda['CensusTract'] = df_usda['CensusTract'].astype(str).str.zfill(11)
df_usda['FIPS'] = df_usda['CensusTract'].str[:5]
df_usda['FIPS']

0        01001
1        01001
2        01001
3        01001
4        01001
         ...
72526    56043
72527    56043
72528    56043
72529    56045
72530    56045
Name: FIPS, Length: 72531, dtype: object

In [7]:
# 2. Clean CDC FIPS
# 'LocationID' is an integer like 1001, but we need 5 digits (01001).
df_cdc['FIPS'] = df_cdc['LocationID'].astype(str).str.zfill(5)
df_cdc['FIPS']

0         01027
1         01045
2         01071
3         01077
4         01079
          ...
240881    55095
240882    55121
240883    55029
240884    55073
240885    56013
Name: FIPS, Length: 240806, dtype: object

In [8]:
# 3. Clean ACS FIPS
# 'GEO_ID' is "0500000US01001," but we need the last 5 digits.
df_acs_econ['FIPS'] = df_acs_econ['GEO_ID'].str.split('US').str[-1]
df_acs_econ['FIPS']

1       01001
2       01003
3       01005
4       01007
5       01009
        ...
3218    72145
3219    72147
3220    72149
3221    72151
3222    72153
Name: FIPS, Length: 3222, dtype: object

In [9]:
df_acs_soc['FIPS'] = df_acs_soc['GEO_ID'].str.split('US').str[-1]
df_acs_soc['FIPS']

1       01001
2       01003
3       01005
4       01007
5       01009
        ...
3218    72145
3219    72147
3220    72149
3221    72151
3222    72153
Name: FIPS, Length: 3222, dtype: object

## STEP 3: Aggregate USDA to county level

In [10]:
# Group by FIPS and extract variables of interest.
# - 'FIPS': Federal Informaton Processing Standards
# - 'lapop1': Population count beyond 1 mile from supermarket
# - 'Pop2010': Population count from 2010 census
# - 'LILATracts_1And10': Flag for low-income and low access when considering low accessibilty at 1 and 10 miles
# - 'Urban': Flag for urban tract
county_food = df_usda.groupby('FIPS').agg({
    'lapop1': 'sum', 
    'Pop2010': 'sum',
    'LILATracts_1And10': 'max',
    'Urban': 'max'  
}).reset_index()

# 'Pct_Low_Access_Pop': Percentage of Low Access Population
county_food['Pct_Low_Access_Pop'] = (county_food['lapop1'] / county_food['Pop2010']) * 100
county_food

       FIPS    lapop1  Pop2010  LILATracts_1And10  Urban  Pct_Low_Access_Pop
0     01001   37424.0    54571                  1      1           68.578549
1     01003  132442.0   182265                  1      1           72.664527
2     01005   19007.0    27457                  1      1           69.224606
3     01007   17560.0    22915                  0      0           76.631028
4     01009   50848.0    57322                  0      1           88.705907
...     ...       ...      ...                ...    ...                 ...
3137  56037   24036.0    43806                  0      1           54.869196
3138  56039   15298.0    21294                  0      1           71.841833
3139  56041   12250.0    21118                  0      0           58.007387
3140  56043    2869.0     8533                  0      1           33.622407
3141  56045    3659.0     7208                  0      1           50.763041

[3142 rows x 6 columns]

## STEP 4: Prepare CDC Health outcomes

In [11]:
# Filter for 3 diseases: diabetes, hypertension, obesity
# - 'Age-adjusted prevalence': to compare the "healthiness" of two counties fairly, removing the bias caused by one county having an older or younger population than the other.
diseases = ['DIABETES', 'BPHIGH', 'OBESITY']
df_cdc_filtered = df_cdc[df_cdc['MeasureId'].isin(diseases) & (df_cdc['Data_Value_Type'] == 'Age-adjusted prevalence')]
df_cdc_filtered

,Year,StateAbbr,StateDesc,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,...,High_Confidence_Limit,TotalPopulation,TotalPop18plus,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text,Geolocation,FIPS
3,2022,AL,Alabama,Lauderdale,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,36.5,...,43.9,"95,878","77,472",1077,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-87.6540983850983 34.9014438477101),01077
9,2021,AL,Alabama,Mobile,BRFSS,Health Outcomes,High blood pressure among adults,%,Age-adjusted prevalence,38.3,...,41.6,"411,411","316,433",1097,HLTHOUT,BPHIGH,AgeAdjPrv,High Blood Pressure,POINT (-88.20640909701 30.7791692937068),01097
13,2022,AK,Alaska,Kodiak Island,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,30.3,...,36.5,"12,720","9,749",2150,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-153.789812278338 57.6808874751479),02150
34,2022,CA,California,Calaveras,BRFSS,Health Outcomes,Diagnosed diabetes among adults,%,Age-adjusted prevalence,9.4,...,10.8,"46,563","38,508",6009,HLTHOUT,DIABETES,AgeAdjPrv,Diabetes,POINT (-120.554047814815 38.2047708244318),06009
39,2022,CA,California,Monterey,BRFSS,Health Outcomes,Diagnosed diabetes among adults,%,Age-adjusted prevalence,11.1,...,12.8,"432,858","322,881",6053,HLTHOUT,DIABETES,AgeAdjPrv,Diabetes,POINT (-121.238518915104 36.2170334850568),06053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240822,2022,WI,Wisconsin,Douglas,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,40.4,...,47.1,"44,144","35,842",55031,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-91.9161252265845 46.4328926127271),55031
240846,2021,WI,Wisconsin,Langlade,BRFSS,Health Outcomes,High blood pressure among adults,%,Age-adjusted prevalence,29.6,...,33.6,"19,559","15,841",55067,HLTHOUT,BPHIGH,AgeAdjPrv,High Blood Pressure,POINT (-89.0718838982873 45.2623121759565),55067
240847,2022,WI,Wisconsin,Chippewa,BRFSS,Health Outcomes,Diagnosed diabetes among adults,%,Age-adjusted prevalence,8.4,...,9.7,"66,807","52,613",55017,HLTHOUT,DIABETES,AgeAdjPrv,Diabetes,POINT (-91.2799726300936 45.0694319590576),55017
240856,2022,WI,Wisconsin,Oneida,BRFSS,Health Outcomes,Diagnosed diabetes among adults,%,Age-adjusted prevalence,8.3,...,9.7,"38,212","31,836",55085,HLTHOUT,DIABETES,AgeAdjPrv,Diabetes,POINT (-89.5218417475047 45.7055064731892),55085
240863,2022,WY,Wyoming,Sheridan,BRFSS,Health Outcomes,Diagnosed diabetes among adults,%,Age-adjusted prevalence,7.9,...,9.0,"32,096","25,473",56033,HLTHOUT,DIABETES,AgeAdjPrv,Diabetes,POINT (-106.87999955798 44.7906982747118),56033

In [12]:
# Group by FIPS, State, County and extract variables of interest
# - 'FIPS': Federal Informaton Processing Standards
# - 'StateDesc': State name
# - 'LocationName': County name
# - 'MeasureId': Measure identifier (Disease)
# - 'Data_Value': Data Value, such as 14.7 (Prevalence)
county_health = df_cdc_filtered.pivot(
    index=['FIPS', 'StateDesc', 'LocationName'], 
    columns='MeasureId', 
    values='Data_Value'
).reset_index()

# Rename the columns
county_health.columns.name = None
county_health = county_health.rename(columns={
    'StateDesc': 'State',
    'LocationName': 'County',
    'DIABETES': 'Diabetes_Prev', 
    'BPHIGH': 'Hypertension_Prev', 
    'OBESITY': 'Obesity_Prev'
})

county_health

,FIPS,State,County,Hypertension_Prev,Diabetes_Prev,Obesity_Prev
0,01001,Alabama,Autauga,37.1,11.3,38.4
1,01003,Alabama,Baldwin,32.4,10.2,36.8
2,01005,Alabama,Barbour,44.1,16.0,43.8
3,01007,Alabama,Bibb,39.1,13.3,41.4
4,01009,Alabama,Blount,35.4,11.6,37.3
...,...,...,...,...,...,...
3139,56037,Wyoming,Sweetwater,28.7,9.4,36.3
3140,56039,Wyoming,Teton,24.1,7.1,22.2
3141,56041,Wyoming,Uinta,27.9,9.0,35.5
3142,56043,Wyoming,Washakie,27.1,9.4,39.1
3143,56045,Wyoming,Weston,27.9,9.6,35.0

## STEP 5: Prepare ACS (Socioeconomic)

In [13]:
# Extract variables of interest
# - 'FIPS': Federal Informaton Processing Standards
# - 'DP03_0062E': Median Household Income (Median)
# - 'DP03_0128PE': Percentage of families and people whose income in the past in the past 12 months is below the poverty level
acs_econ_clean = df_acs_econ[['FIPS', 'DP03_0062E', 'DP03_0128PE']].copy()

# Rename the columns
acs_econ_clean = acs_econ_clean.rename(columns={
    'DP03_0062E': 'Median_Income',
    'DP03_0128PE': 'Poverty_Rate'
})

# Convert to numeric
# 'errors=coerce' turns non-numbers (like "-") into NaN
acs_econ_clean['Median_Income'] = pd.to_numeric(acs_econ_clean['Median_Income'], errors='coerce')
acs_econ_clean['Poverty_Rate'] = pd.to_numeric(acs_econ_clean['Poverty_Rate'], errors='coerce')

acs_econ_clean

       FIPS  Median_Income  Poverty_Rate
1     01001        69841.0          10.7
2     01003        75019.0          10.5
3     01005        44290.0          21.9
4     01007        51215.0          20.5
5     01009        61096.0          14.1
...     ...            ...           ...
3218  72145        23877.0          42.3
3219  72147        17531.0          59.5
3220  72149        24882.0          41.8
3221  72151        21279.0          49.7
3222  72153        21918.0          44.6

[3222 rows x 3 columns]

In [14]:
# Extract variables of interest
# - 'FIPS': Federal Informaton Processing Standards
# - 'DP02_0068PE': Educational attainment - population 25 years and over, bachelor's degree or higher
acs_soc_clean = df_acs_soc[['FIPS', 'DP02_0068PE']].copy()
acs_soc_clean = acs_soc_clean.rename(columns={
    'DP02_0068PE': 'Bachelors_Degree_Pct'
})

# Convert to numeric
# 'errors=coerce' turns non-numbers (like "-") into NaN
acs_soc_clean['Bachelors_Degree_Pct'] = pd.to_numeric(acs_soc_clean['Bachelors_Degree_Pct'], errors='coerce')
acs_soc_clean

       FIPS  Bachelors_Degree_Pct
1     01001                  28.3
2     01003                  32.8
3     01005                  11.5
4     01007                  11.5
5     01009                  15.6
...     ...                   ...
3218  72145                   NaN
3219  72147                   NaN
3220  72149                   NaN
3221  72151                   NaN
3222  72153                   NaN

[3222 rows x 2 columns]

## STEP 6: Merge datasets

In [15]:
# 1. Outer Merge: Socio + Economic Status
county_ses = pd.merge(acs_econ_clean, acs_soc_clean, on='FIPS', how='outer')
county_ses

       FIPS  Median_Income  Poverty_Rate  Bachelors_Degree_Pct
0     01001        69841.0          10.7                  28.3
1     01003        75019.0          10.5                  32.8
2     01005        44290.0          21.9                  11.5
3     01007        51215.0          20.5                  11.5
4     01009        61096.0          14.1                  15.6
...     ...            ...           ...                   ...
3217  72145        23877.0          42.3                   NaN
3218  72147        17531.0          59.5                   NaN
3219  72149        24882.0          41.8                   NaN
3220  72151        21279.0          49.7                   NaN
3221  72153        21918.0          44.6                   NaN

[3222 rows x 4 columns]

In [16]:
# 2. Inner Merge: Food + Health
master = pd.merge(county_food, county_health, on='FIPS', how='inner')
master

,FIPS,lapop1,Pop2010,LILATracts_1And10,Urban,Pct_Low_Access_Pop,State,County,Hypertension_Prev,Diabetes_Prev,Obesity_Prev
0,01001,37424.0,54571,1,1,68.578549,Alabama,Autauga,37.1,11.3,38.4
1,01003,132442.0,182265,1,1,72.664527,Alabama,Baldwin,32.4,10.2,36.8
2,01005,19007.0,27457,1,1,69.224606,Alabama,Barbour,44.1,16.0,43.8
3,01007,17560.0,22915,0,0,76.631028,Alabama,Bibb,39.1,13.3,41.4
4,01009,50848.0,57322,0,1,88.705907,Alabama,Blount,35.4,11.6,37.3
...,...,...,...,...,...,...,...,...,...,...,...
3128,56037,24036.0,43806,0,1,54.869196,Wyoming,Sweetwater,28.7,9.4,36.3
3129,56039,15298.0,21294,0,1,71.841833,Wyoming,Teton,24.1,7.1,22.2
3130,56041,12250.0,21118,0,0,58.007387,Wyoming,Uinta,27.9,9.0,35.5
3131,56043,2869.0,8533,0,1,33.622407,Wyoming,Washakie,27.1,9.4,39.1
3132,56045,3659.0,7208,0,1,50.763041,Wyoming,Weston,27.9,9.6,35.0

In [17]:
# 3. Inner Merge: (Food + Health) + Socioeconomic Status
master = pd.merge(master, county_ses, on='FIPS', how='inner')
master

,FIPS,lapop1,Pop2010,LILATracts_1And10,Urban,Pct_Low_Access_Pop,State,County,Hypertension_Prev,Diabetes_Prev,Obesity_Prev,Median_Income,Poverty_Rate,Bachelors_Degree_Pct
0,01001,37424.0,54571,1,1,68.578549,Alabama,Autauga,37.1,11.3,38.4,69841.0,10.7,28.3
1,01003,132442.0,182265,1,1,72.664527,Alabama,Baldwin,32.4,10.2,36.8,75019.0,10.5,32.8
2,01005,19007.0,27457,1,1,69.224606,Alabama,Barbour,44.1,16.0,43.8,44290.0,21.9,11.5
3,01007,17560.0,22915,0,0,76.631028,Alabama,Bibb,39.1,13.3,41.4,51215.0,20.5,11.5
4,01009,50848.0,57322,0,1,88.705907,Alabama,Blount,35.4,11.6,37.3,61096.0,14.1,15.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3128,56037,24036.0,43806,0,1,54.869196,Wyoming,Sweetwater,28.7,9.4,36.3,76464.0,13.4,20.4
3129,56039,15298.0,21294,0,1,71.841833,Wyoming,Teton,24.1,7.1,22.2,112681.0,7.0,61.2
3130,56041,12250.0,21118,0,0,58.007387,Wyoming,Uinta,27.9,9.0,35.5,82672.0,7.6,21.3
3131,56043,2869.0,8533,0,1,33.622407,Wyoming,Washakie,27.1,9.4,39.1,62648.0,8.6,22.0
3132,56045,3659.0,7208,0,1,50.763041,Wyoming,Weston,27.9,9.6,35.0,87545.0,10.5,18.0

## STEP 7: Clean the data

In [18]:
# 1. Check how many rows we have
print(f"Counties before dropping nulls: {len(master)}")

Counties before dropping nulls: 3133

In [19]:
# 2. Drop rows if they are missing critical data
master_clean = master.dropna(subset=['Pct_Low_Access_Pop', 'Diabetes_Prev', 'Hypertension_Prev', 'Obesity_Prev', 'Median_Income', 'Poverty_Rate', 'Bachelors_Degree_Pct'])

print(f"Counties after dropping nulls: {len(master_clean)}")
master_clean

Counties after dropping nulls: 3064

,FIPS,lapop1,Pop2010,LILATracts_1And10,Urban,Pct_Low_Access_Pop,State,County,Hypertension_Prev,Diabetes_Prev,Obesity_Prev,Median_Income,Poverty_Rate,Bachelors_Degree_Pct
0,01001,37424.0,54571,1,1,68.578549,Alabama,Autauga,37.1,11.3,38.4,69841.0,10.7,28.3
1,01003,132442.0,182265,1,1,72.664527,Alabama,Baldwin,32.4,10.2,36.8,75019.0,10.5,32.8
2,01005,19007.0,27457,1,1,69.224606,Alabama,Barbour,44.1,16.0,43.8,44290.0,21.9,11.5
3,01007,17560.0,22915,0,0,76.631028,Alabama,Bibb,39.1,13.3,41.4,51215.0,20.5,11.5
4,01009,50848.0,57322,0,1,88.705907,Alabama,Blount,35.4,11.6,37.3,61096.0,14.1,15.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3128,56037,24036.0,43806,0,1,54.869196,Wyoming,Sweetwater,28.7,9.4,36.3,76464.0,13.4,20.4
3129,56039,15298.0,21294,0,1,71.841833,Wyoming,Teton,24.1,7.1,22.2,112681.0,7.0,61.2
3130,56041,12250.0,21118,0,0,58.007387,Wyoming,Uinta,27.9,9.0,35.5,82672.0,7.6,21.3
3131,56043,2869.0,8533,0,1,33.622407,Wyoming,Washakie,27.1,9.4,39.1,62648.0,8.6,22.0
3132,56045,3659.0,7208,0,1,50.763041,Wyoming,Weston,27.9,9.6,35.0,87545.0,10.5,18.0

In [20]:
# 3. Reorder columns
cols = ['FIPS', 'State', 'County', 'Diabetes_Prev', 'Hypertension_Prev', 'Obesity_Prev', 'Pct_Low_Access_Pop', 'Median_Income', 'Poverty_Rate', 'Bachelors_Degree_Pct', 'Urban']
remaining = [c for c in master_clean.columns if c not in cols]

master_clean = master_clean[cols + remaining]
master_clean

,FIPS,State,County,Diabetes_Prev,Hypertension_Prev,Obesity_Prev,Pct_Low_Access_Pop,Median_Income,Poverty_Rate,Bachelors_Degree_Pct,Urban,lapop1,Pop2010,LILATracts_1And10
0,01001,Alabama,Autauga,11.3,37.1,38.4,68.578549,69841.0,10.7,28.3,1,37424.0,54571,1
1,01003,Alabama,Baldwin,10.2,32.4,36.8,72.664527,75019.0,10.5,32.8,1,132442.0,182265,1
2,01005,Alabama,Barbour,16.0,44.1,43.8,69.224606,44290.0,21.9,11.5,1,19007.0,27457,1
3,01007,Alabama,Bibb,13.3,39.1,41.4,76.631028,51215.0,20.5,11.5,0,17560.0,22915,0
4,01009,Alabama,Blount,11.6,35.4,37.3,88.705907,61096.0,14.1,15.6,1,50848.0,57322,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3128,56037,Wyoming,Sweetwater,9.4,28.7,36.3,54.869196,76464.0,13.4,20.4,1,24036.0,43806,0
3129,56039,Wyoming,Teton,7.1,24.1,22.2,71.841833,112681.0,7.0,61.2,1,15298.0,21294,0
3130,56041,Wyoming,Uinta,9.0,27.9,35.5,58.007387,82672.0,7.6,21.3,0,12250.0,21118,0
3131,56043,Wyoming,Washakie,9.4,27.1,39.1,33.622407,62648.0,8.6,22.0,1,2869.0,8533,0
3132,56045,Wyoming,Weston,9.6,27.9,35.0,50.763041,87545.0,10.5,18.0,1,3659.0,7208,0

# Method 2: DESCRIPTIVE ANALYSIS

In [21]:
# 1. SAMPLE SIZE (N)
print(f"\n1. Sample Size:")
print(f"Total Counties in Analysis (N): {len(master_clean)}")

1. Sample Size:
Total Counties in Analysis (N): 3064

In [22]:
# 2. Independent Variable (Food Access)
print(f"2. Food Insecurity (Low Access %)")
print(f"Mean: {master['Pct_Low_Access_Pop'].mean():.2f}%")
print(f"SD:   {master['Pct_Low_Access_Pop'].std():.2f}%")

2. Food Insecurity (Low Access %)
Mean: 64.26%
SD:   19.51%

In [23]:
# 3. Dependent Variables (Diabetes, Hypertension, Obesity)
print(f"3. Health Outcomes")

diseases = ['Diabetes_Prev', 'Hypertension_Prev', 'Obesity_Prev']
for col in diseases:
    mean_val = master_clean[col].mean()
    sd_val = master_clean[col].std()
    print(f"{col}: Mean = {mean_val:.2f}% (SD = {sd_val:.2f})")

3. Health Outcomes
Diabetes_Prev: Mean = 11.14% (SD = 2.31)
Hypertension_Prev: Mean = 32.67% (SD = 4.74)
Obesity_Prev: Mean = 37.97% (SD = 4.63)

In [24]:
# 4. Moderators (SES)
print(f"4. Socioeconomic Context")
# Income
inc_mean = master_clean['Median_Income'].mean()
inc_sd = master_clean['Median_Income'].std()
print(f"   Median Household Income: ${inc_mean:,.0f} (SD: ${inc_sd:,.0f})")

# Poverty
pov_mean = master_clean['Poverty_Rate'].mean()
pov_sd = master_clean['Poverty_Rate'].std()
print(f"   Poverty Rate: {pov_mean:.2f}% (SD: {pov_sd:.2f}%)")

# Education (The missing piece!)
edu_mean = master_clean['Bachelors_Degree_Pct'].mean()
edu_sd = master_clean['Bachelors_Degree_Pct'].std()
print(f"   Bachelor's Degree %: {edu_mean:.2f}% (SD: {edu_sd:.2f}%)")

4. Socioeconomic Context
   Median Household Income: $65,996 (SD: $17,418)
   Poverty Rate: 14.26% (SD: 5.97%)
   Bachelor's Degree %: 24.01% (SD: 10.15%)

# Method 3: BIVARIATE ANALYSIS

In [25]:
# Hypothesis 1
print("1. Hypothesis 1\n")
for d in diseases:
    # Note: If Hypertension still has NaNs even in 'clean', dropna ensures safety
    clean_subset = master_clean.dropna(subset=[d]) 
    
    r, p = pearsonr(clean_subset['Pct_Low_Access_Pop'], clean_subset[d])
    
    # Format p-value string
    p_text = "< 0.001" if p < 0.001 else f"= {p:.3f}"
    sig_text = "**SIGNIFICANT**" if p < 0.05 else "Not Significant"
    
    print(f"{d} vs. Food Access (N={len(clean_subset)}):")
    print(f"   r = {r:.3f}")
    print(f"   p {p_text}  --> {sig_text}")
    print("-" * 30)

1. Hypothesis 1

Diabetes_Prev vs. Food Access (N=3064):
   r = 0.101
   p < 0.001  --> **SIGNIFICANT**
------------------------------
Hypertension_Prev vs. Food Access (N=3064):
   r = 0.260
   p < 0.001  --> **SIGNIFICANT**
------------------------------
Obesity_Prev vs. Food Access (N=3064):
   r = 0.229
   p < 0.001  --> **SIGNIFICANT**
------------------------------

# Method 4: STRATIFIED ANALYSIS

In [26]:
# Hypothesis 2: Income
print("2-1. Hypothesis 2: Income")

for d in diseases:
    # Split income into 'High Income Group' and 'Low Income Group'
    median_inc = master_clean['Median_Income'].median()
    low_inc = master_clean[master_clean['Median_Income'] < median_inc]
    high_inc = master_clean[master_clean['Median_Income'] >= median_inc]

    print(f"\nAverage {d}:")
    print(f"Low Income Group:  {low_inc[d].mean():.2f}%")
    print(f"High Income Group: {high_inc[d].mean():.2f}%")

    # Test: Does the Food-Disease link disappear in low income counties?
    r_low, _ = pearsonr(low_inc['Pct_Low_Access_Pop'], low_inc[d])
    r_high, _ = pearsonr(high_inc['Pct_Low_Access_Pop'], high_inc[d])

    print(f"\nCorrelation:")
    print(f"Low Income Group:   r = {r_low:.3f}")
    print(f"High Income Group:  r = {r_high:.3f}")
    print("-" * 30)

2-1. Hypothesis 2: Income

Average Diabetes_Prev:
Low Income Group:  12.34%
High Income Group: 9.93%

Correlation:
Low Income Group:   r = 0.008
High Income Group:  r = -0.049
------------------------------

Average Hypertension_Prev:
Low Income Group:  35.32%
High Income Group: 30.02%

Correlation:
Low Income Group:   r = 0.178
High Income Group:  r = 0.171
------------------------------

Average Obesity_Prev:
Low Income Group:  40.01%
High Income Group: 35.94%

Correlation:
Low Income Group:   r = 0.052
High Income Group:  r = 0.222
------------------------------

In [27]:
# Hypothesis 2: Poverty
print("2-2. Hypothesis 2: Poverty")

for d in diseases:
    # Split income into 'High Poverty Group' and 'Low Poverty Group'
    median_pov = master_clean['Poverty_Rate'].median()
    low_pov = master_clean[master_clean['Poverty_Rate'] < median_pov]
    high_pov = master_clean[master_clean['Poverty_Rate'] >= median_pov]

    print(f"\nAverage {d}:")
    print(f"Low Poverty Group:  {low_pov[d].mean():.2f}%")
    print(f"High Poverty Group: {high_pov[d].mean():.2f}%")

    # Test: Does the Food-Disease link disappear in low poverty counties?
    r_low, _ = pearsonr(low_pov['Poverty_Rate'], low_pov[d])
    r_high, _ = pearsonr(high_pov['Poverty_Rate'], high_pov[d])

    print(f"\nCorrelation:")
    print(f"Low Poverty Group:   r = {r_low:.3f}")
    print(f"High Poverty Group:  r = {r_high:.3f}")
    print("-" * 30)

2-2. Hypothesis 2: Poverty

Average Diabetes_Prev:
Low Poverty Group:  9.77%
High Poverty Group: 12.50%

Correlation:
Low Poverty Group:   r = 0.316
High Poverty Group:  r = 0.645
------------------------------

Average Hypertension_Prev:
Low Poverty Group:  29.92%
High Poverty Group: 35.41%

Correlation:
Low Poverty Group:   r = 0.348
High Poverty Group:  r = 0.541
------------------------------

Average Obesity_Prev:
Low Poverty Group:  36.15%
High Poverty Group: 39.80%

Correlation:
Low Poverty Group:   r = 0.249
High Poverty Group:  r = 0.452
------------------------------

In [28]:
# Hypothesis 2: Education
print("2-3. Hypothesis 2: Education")

for d in diseases:
    # Split income into 'High Education Group' and 'Low Education Group'
    median_edu = master_clean['Bachelors_Degree_Pct'].median()
    low_edu = master_clean[master_clean['Bachelors_Degree_Pct'] < median_edu]
    high_edu = master_clean[master_clean['Bachelors_Degree_Pct'] >= median_edu]

    print(f"\nAverage {d}:")
    print(f"Low Education Group:  {low_edu[d].mean():.2f}%")
    print(f"High Education Group: {high_edu[d].mean():.2f}%")

    # Test: Does the Food-Disease link disappear in low education counties?
    r_low, _ = pearsonr(low_edu['Bachelors_Degree_Pct'], low_edu[d])
    r_high, _ = pearsonr(high_edu['Bachelors_Degree_Pct'], high_edu[d])

    print(f"\nCorrelation:")
    print(f"Low Education Group:   r = {r_low:.3f}")
    print(f"High Education Group:  r = {r_high:.3f}")
    print("-" * 30)

2-3. Hypothesis 2: Education

Average Diabetes_Prev:
Low Education Group:  12.28%
High Education Group: 10.00%

Correlation:
Low Education Group:   r = -0.468
High Education Group:  r = -0.310
------------------------------

Average Hypertension_Prev:
Low Education Group:  34.95%
High Education Group: 30.40%

Correlation:
Low Education Group:   r = -0.435
High Education Group:  r = -0.365
------------------------------

Average Obesity_Prev:
Low Education Group:  40.18%
High Education Group: 35.79%

Correlation:
Low Education Group:   r = -0.322
High Education Group:  r = -0.601
------------------------------

# Method 5: GROUPED COMPARISION

In [29]:
# Hypothesis 3
print("Hypothesis 3: Rural vs Urban\n")

# 0 = Rural, 1 = Urban
rural = master_clean[master_clean['Urban'] == 0]
urban = master_clean[master_clean['Urban'] == 1]

# for each disease, calculate average prevalence in rural/urban, t-test p-value and derive result
for d in diseases:
    print(f"\n--- {d} ---")
    mean_rural = rural[d].mean()
    mean_urban = urban[d].mean()
    
    print(f"   Avg Prevalence (Rural): {mean_rural:.2f}% (N={len(rural)})")
    print(f"   Avg Prevalence (Urban): {mean_urban:.2f}% (N={len(urban)})")
    
    # Independent T-Test
    t_stat, p_val = ttest_ind(rural[d], urban[d], nan_policy='omit', equal_var=False)
    
    print(f"   T-Test p-value: {p_val:.3f}")
    if p_val < 0.05:
        print("   Result: SIGNIFICANT Difference")
    else:
        print("   Result: No Significant Difference")

Hypothesis 3: Rural vs Urban


--- Diabetes_Prev ---
   Avg Prevalence (Rural): 11.20% (N=960)
   Avg Prevalence (Urban): 11.11% (N=2104)
   T-Test p-value: 0.334
   Result: No Significant Difference

--- Hypertension_Prev ---
   Avg Prevalence (Rural): 33.08% (N=960)
   Avg Prevalence (Urban): 32.48% (N=2104)
   T-Test p-value: 0.001
   Result: SIGNIFICANT Difference

--- Obesity_Prev ---
   Avg Prevalence (Rural): 38.43% (N=960)
   Avg Prevalence (Urban): 37.77% (N=2104)
   T-Test p-value: 0.000
   Result: SIGNIFICANT Difference

# Method 6: DATA EXPORT

In [30]:
# Save the final version for data visusalization (tableau)
output_filename = "HINF5004_Final_Project_Data_Analysis.csv"
master_clean.to_csv(output_filename, index=False)